# apiVersion: security.istio.io/v1beta1
# kind: PeerAuthentication
# metadata:
#   name: user-manager-mtls-policy
# spec:
#   selector:
#     matchLabels:
#       app: user-manager
#   mtls:
#     mode: PERMISSIVE
# ---
# apiVersion: security.istio.io/v1beta1
# kind: AuthorizationPolicy
# metadata:
#   name: user-manager-auth-policy
# spec:
#   selector:
#     matchLabels:
#       app: user-manager
#   action: ALLOW
  # - from:
  #   - source:
  #       principals: ["cluster.local/ns/default/sa/public-user-manager-api"]
